### Create product
POST http://localhost:8080/api/products
Content-Type: application/json
Accept: application/json

{
  "id" : "A0010",
  "name" : "Mac Book Pro 15",
  "price" : 30000000,
  "quantity" : 10
}

### validation create product error
POST http://localhost:8080/api/products
Content-Type: application/json
Accept: application/json

{
  "id" : "",
  "name" : "",
  "price" : 0,
  "quantity" : -10
}


### get product
GET http://localhost:8080/api/products/A0010
Accept: application/json

### get product not found
GET http://localhost:8080/api/products/SALAH
Accept: application/json

### Update product

PUT http://localhost:8080/api/products/A0010
X-Api-Key: SECRET
Content-Type: application/json
Accept: application/json

{
  "name" : "Apple Mac Book Pro 15 2020",
  "price" : 40000000,
  "quantity" : 100
}

### Update product not found

PUT http://localhost:8080/api/products/SALAH
X-Api-Key: SECRET
Content-Type: application/json
Accept: application/json

{
  "name" : "Apple Mac Book Pro 15 2020",
  "price" : 40000000,
  "quantity" : 100
}

### Update product with invalid body

PUT http://localhost:8080/api/products/A0010
X-Api-Key: SECRET
Content-Type: application/json
Accept: application/json

{
  "name" : "",
  "price" : 0,
  "quantity" : -10
}

### Delete product (content type kalau punya body)

DELETE http://localhost:8080/api/products/A0010
X-Api-Key: SECRET
Accept: application/json

